name: Docker Image CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: "echo "$APPLICATION_CONFIG" > config.json"
        shell: bash
        env:
          SSH_KEY: ${{secrets.APPLICATION_CONFIG}} 
          
      # Build the image
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
