name: Docker Image CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$APPLICATION_CONFIG" > config.json'
        shell: bash
        env:
          APPLICATION_CONFIG: ${{secrets.APPLICATION_CONFIG}} 
      # Build the image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hackpack-bot:$(date +%s)
