name: Rust

on:
  push:
    branches: [ main, fix_clippy_check ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: clippy-check
      uses: tcheinen/clippy-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
